In [1]:
import numpy as np

In [2]:
a=np.arange(10)
b=np.arange(20)

In [3]:
a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
a=np.arange(9)
b=range(7)

In [5]:
print(a)
print(b)

[0 1 2 3 4 5 6 7 8]
range(0, 7)


In [6]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

2
(4, 5)
20
int32
4
<class 'numpy.ndarray'>


In [8]:
a = np.array( [4.0, 5.0, 6.0, 7.0] )
print(a)
print(a.dtype)
print(type(a))

[4. 5. 6. 7.]
float64
<class 'numpy.ndarray'>


In [9]:
c = np.eye(5)
dtype=np.float64
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
a= np.linspace(0,5,11, endpoint=True)
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [11]:
a=np.logspace(0,5,11, endpoint=False)
print(a)

[1.00000000e+00 2.84803587e+00 8.11130831e+00 2.31012970e+01
 6.57933225e+01 1.87381742e+02 5.33669923e+02 1.51991108e+03
 4.32876128e+03 1.23284674e+04 3.51119173e+04]


In [12]:
y = np.fromfunction(lambda i, j: i == j, (2, 2), dtype=int)
y

array([[ True, False],
       [False,  True]])

In [54]:
b= np.arange(12).reshape(2,6)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [55]:
a*2

array([2.00000000e+00, 5.69607174e+00, 1.62226166e+01, 4.62025940e+01,
       1.31586645e+02, 3.74763485e+02, 1.06733985e+03, 3.03982217e+03,
       8.65752256e+03, 2.46569348e+04, 7.02238347e+04])

In [56]:
a+2

array([3.00000000e+00, 4.84803587e+00, 1.01113083e+01, 2.51012970e+01,
       6.77933225e+01, 1.89381742e+02, 5.35669923e+02, 1.52191108e+03,
       4.33076128e+03, 1.23304674e+04, 3.51139173e+04])

In [57]:
a*a

array([1.00000000e+00, 8.11130831e+00, 6.57933225e+01, 5.33669923e+02,
       4.32876128e+03, 3.51119173e+04, 2.84803587e+05, 2.31012970e+06,
       1.87381742e+07, 1.51991108e+08, 1.23284674e+09])

In [59]:
print(a)
b= a.transpose()
b

[1.00000000e+00 2.84803587e+00 8.11130831e+00 2.31012970e+01
 6.57933225e+01 1.87381742e+02 5.33669923e+02 1.51991108e+03
 4.32876128e+03 1.23284674e+04 3.51119173e+04]


array([1.00000000e+00, 2.84803587e+00, 8.11130831e+00, 2.31012970e+01,
       6.57933225e+01, 1.87381742e+02, 5.33669923e+02, 1.51991108e+03,
       4.32876128e+03, 1.23284674e+04, 3.51119173e+04])

In [60]:
a@b

1406211004.5060644

In [73]:
b= np.arange(8).reshape(2,4)
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [77]:
print(b)
a.sum(axis=0)

[[0 1 2 3]
 [4 5 6 7]]


54110.96272965751

In [79]:
print(b.min(), b.max())

0 7


In [85]:
a= np.arange(8).reshape(2,4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [86]:
b=a*np.pi/12
print(b)

[[0.         0.26179939 0.52359878 0.78539816]
 [1.04719755 1.30899694 1.57079633 1.83259571]]


In [89]:
c=np.sin(b)
print(c)

[[0.         0.25881905 0.5        0.70710678]
 [0.8660254  0.96592583 1.         0.96592583]]


In [90]:
D=b+c
print(D)

[[0.         0.52061843 1.02359878 1.49250494]
 [1.91322295 2.27492277 2.57079633 2.79852154]]


In [91]:
cap=np.arange(50)
cap
even=cap[0:50:2]
print(even)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [92]:
cap=np.arange(50)
cap
odd=cap[0:50:3]
print(odd)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [93]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [94]:
a[6]

6

In [95]:
a[2:15]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [96]:
a[5:20:2]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [97]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [107]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [110]:
a[1,2]

7

In [112]:
a[0:2,0:4]

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [113]:
a[:,2]

array([ 2,  7, 12, 17, 22])

In [115]:
a=a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [124]:
for mangalore in a:
    print(mangalore)
a=np.arange(36).reshape(6,6)
print(a
    )

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [125]:
for e in a.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35


In [126]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [127]:
b=a
b is a

True

In [130]:
b.shape=(6,2)
print(b)
a.shape

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


(6, 2)

In [131]:
b is a

True

In [132]:
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [133]:
a = np.arange(12)
c = a[:]
a.shape = (6,2)

print(a)
print(c)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [134]:
c[1] = -1
print(a)
print(c)

[[ 0 -1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [135]:
d = c[4:9]
print(d)

[4 5 6 7 8]


In [137]:
d[:]=0
d

array([0, 0, 0, 0, 0])

In [138]:
print(a)
print(c)
print(d)


[[ 0 -1]
 [ 2  3]
 [ 0  0]
 [ 0  0]
 [ 0  9]
 [10 11]]
[ 0 -1  2  3  0  0  0  0  0  9 10 11]
[0 0 0 0 0]


In [139]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [140]:
a[a > 4] = 0
a

array([[0, 1, 2, 3, 4, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [141]:
a[a == 0] = -1
a

array([[-1,  1,  2,  3,  4, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1]])

In [142]:
a == -1

array([[ True, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [143]:
a = np.arange(9).reshape(3,3)
a[np.logical_and(a > 3, a <= 9)] = 0.0
a

array([[0, 1, 2],
       [3, 0, 0],
       [0, 0, 0]])

In [144]:
a>4

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [146]:
M = 12
N = 24
xmin = ymin = 0.0
xmax = ymax = 1.0

x = np.linspace(xmin, xmax, M, endpoint=True)
y = np.linspace(ymin, ymax, N, endpoint=True)

print(x.shape)
print(y.shape)
y

(12,)
(24,)


array([0.        , 0.04347826, 0.08695652, 0.13043478, 0.17391304,
       0.2173913 , 0.26086957, 0.30434783, 0.34782609, 0.39130435,
       0.43478261, 0.47826087, 0.52173913, 0.56521739, 0.60869565,
       0.65217391, 0.69565217, 0.73913043, 0.7826087 , 0.82608696,
       0.86956522, 0.91304348, 0.95652174, 1.        ])

In [147]:
import time
M = 12
N = 24

x = np.linspace(0.0, 1.0, M, endpoint=False)
y = np.linspace(0.0, 1.0, N, endpoint=False)


In [153]:
t0 = time.time()

g = np.zeros((M, N))

for i in range(M):
    for j in range(N):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
        
t1 = time.time()
print("time taken: {} s".format(t1-t0))

time taken: 0.0009968280792236328 s


In [154]:
x2d, y2d = np.meshgrid(x, y, indexing="ij")

print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

[0.         0.08333333 0.16666667 0.25       0.33333333 0.41666667
 0.5        0.58333333 0.66666667 0.75       0.83333333 0.91666667]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333]


In [155]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0 s


In [156]:
xman=np.array([7,8,9,5])
yman=np.array([1,2,3,4])
np.concatenate([xman,yman])

array([7, 8, 9, 5, 1, 2, 3, 4])

In [157]:
zman = [19, 14, 10]
print(np.concatenate([xman, yman, zman]))

[ 7  8  9  5  1  2  3  4 19 14 10]


In [158]:
grid = np.array([[11, 21, 13],
                 [12, 15, 16]])

In [159]:
np.concatenate([grid, grid])

array([[11, 21, 13],
       [12, 15, 16],
       [11, 21, 13],
       [12, 15, 16]])

In [161]:
np.concatenate([grid, grid], axis=1)

array([[11, 21, 13, 11, 21, 13],
       [12, 15, 16, 12, 15, 16]])

In [162]:
x = [2, 3, 4, 5, 4, 3 ,2, 1, 9, 4 ,6]
x1, x2, x3,x4 = np.split(x, [2, 6,9])
print(x1, x2, x3, x4)

[2 3] [4 5 4 3] [2 1 9] [4 6]


In [164]:
grid = np.arange(30).reshape((3, 10))
grid

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [165]:
right, left = np.hsplit(grid, [3])
print(left)
print(right)

[[ 3  4  5  6  7  8  9]
 [13 14 15 16 17 18 19]
 [23 24 25 26 27 28 29]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]


In [166]:
x = np.arange(10, 20)
print(x)
np.add.reduce(x)

[10 11 12 13 14 15 16 17 18 19]


145

In [167]:
np.multiply.reduce(x)

213837312

In [168]:
np.add.accumulate(x)

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145], dtype=int32)

In [169]:
np.multiply.accumulate(x)

array([       10,       110,      1320,     17160,    240240,   3603600,
        57657600, 980179200, 463356416, 213837312], dtype=int32)